# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FormGame.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QTextBrowser, QWidget)

class Ui_FormGame(object):
    def setupUi(self, FormGame):
        if not FormGame.objectName():
            FormGame.setObjectName(u"FormGame")
        FormGame.resize(1440, 810)
        FormGame.setMinimumSize(QSize(1440, 810))
        FormGame.setMaximumSize(QSize(1440, 810))
        self.actionShowCollections = QAction(FormGame)
        self.actionShowCollections.setObjectName(u"actionShowCollections")
        self.actionShowAdjustments = QAction(FormGame)
        self.actionShowAdjustments.setObjectName(u"actionShowAdjustments")
        self.actionShowCurrentAdjustments = QAction(FormGame)
        self.actionShowCurrentAdjustments.setObjectName(u"actionShowCurrentAdjustments")
        self.actionConsole = QAction(FormGame)
        self.actionConsole.setObjectName(u"actionConsole")
        self.centralwidget = QWidget(FormGame)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textEvent = QTextBrowser(self.centralwidget)
        self.textEvent.setObjectName(u"textEvent")
        self.textEvent.setGeometry(QRect(10, 30, 731, 431))
        self.listActions = QListWidget(self.centralwidget)
        self.listActions.setObjectName(u"listActions")
        self.listActions.setGeometry(QRect(1170, 330, 256, 321))
        self.buttonContinue = QPushButton(self.centralwidget)
        self.buttonContinue.setObjectName(u"buttonContinue")
        self.buttonContinue.setGeometry(QRect(1170, 660, 261, 91))
        self.labelEvent = QLabel(self.centralwidget)
        self.labelEvent.setObjectName(u"labelEvent")
        self.labelEvent.setGeometry(QRect(20, 10, 60, 15))
        self.labelAction = QLabel(self.centralwidget)
        self.labelAction.setObjectName(u"labelAction")
        self.labelAction.setGeometry(QRect(1170, 310, 60, 15))
        self.labelCheck = QLabel(self.centralwidget)
        self.labelCheck.setObjectName(u"labelCheck")
        self.labelCheck.setGeometry(QRect(770, 10, 251, 16))
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(750, 410, 411, 351))
        self.pageCollections = QWidget()
        self.pageCollections.setObjectName(u"pageCollections")
        self.listItems = QListWidget(self.pageCollections)
        self.listItems.setObjectName(u"listItems")
        self.listItems.setGeometry(QRect(10, 50, 380, 291))
        self.labelItems = QLabel(self.pageCollections)
        self.labelItems.setObjectName(u"labelItems")
        self.labelItems.setGeometry(QRect(10, 30, 60, 15))
        self.stackedWidget.addWidget(self.pageCollections)
        self.pageAdjustments = QWidget()
        self.pageAdjustments.setObjectName(u"pageAdjustments")
        self.listAdjustments = QListWidget(self.pageAdjustments)
        self.listAdjustments.setObjectName(u"listAdjustments")
        self.listAdjustments.setGeometry(QRect(10, 50, 380, 291))
        self.labelAdjustments = QLabel(self.pageAdjustments)
        self.labelAdjustments.setObjectName(u"labelAdjustments")
        self.labelAdjustments.setGeometry(QRect(10, 30, 60, 15))
        self.stackedWidget.addWidget(self.pageAdjustments)
        self.pageCurrentAdjuetments = QWidget()
        self.pageCurrentAdjuetments.setObjectName(u"pageCurrentAdjuetments")
        self.labelCurrentAdjustments = QLabel(self.pageCurrentAdjuetments)
        self.labelCurrentAdjustments.setObjectName(u"labelCurrentAdjustments")
        self.labelCurrentAdjustments.setGeometry(QRect(10, 30, 240, 15))
        self.listAdjustments_2 = QListWidget(self.pageCurrentAdjuetments)
        self.listAdjustments_2.setObjectName(u"listAdjustments_2")
        self.listAdjustments_2.setGeometry(QRect(10, 50, 380, 291))
        self.stackedWidget.addWidget(self.pageCurrentAdjuetments)
        self.buttonReroll = QPushButton(self.centralwidget)
        self.buttonReroll.setObjectName(u"buttonReroll")
        self.buttonReroll.setGeometry(QRect(760, 340, 151, 71))
        self.textInfo = QTextBrowser(self.centralwidget)
        self.textInfo.setObjectName(u"textInfo")
        self.textInfo.setGeometry(QRect(10, 490, 731, 261))
        self.labelInfo = QLabel(self.centralwidget)
        self.labelInfo.setObjectName(u"labelInfo")
        self.labelInfo.setGeometry(QRect(20, 470, 60, 15))
        self.labelPossibility = QLabel(self.centralwidget)
        self.labelPossibility.setObjectName(u"labelPossibility")
        self.labelPossibility.setGeometry(QRect(1210, 20, 200, 31))
        font = QFont()
        font.setFamilies([u"\u534e\u6587\u7ec6\u9ed1"])
        font.setPointSize(14)
        self.labelPossibility.setFont(font)
        self.labelPossibility.setAlignment(Qt.AlignCenter)
        self.labelPossibility.setMargin(0)
        self.dice1 = QPushButton(self.centralwidget)
        self.dice1.setObjectName(u"dice1")
        self.dice1.setGeometry(QRect(770, 30, 100, 100))
        self.dice1.setStyleSheet(u"border:none;")
        self.dice1.setIconSize(QSize(100, 100))
        self.dice2 = QPushButton(self.centralwidget)
        self.dice2.setObjectName(u"dice2")
        self.dice2.setGeometry(QRect(900, 30, 100, 100))
        self.dice2.setStyleSheet(u"border:none;")
        self.dice2.setIconSize(QSize(100, 100))
        self.dice3 = QPushButton(self.centralwidget)
        self.dice3.setObjectName(u"dice3")
        self.dice3.setGeometry(QRect(1050, 30, 100, 100))
        self.dice3.setStyleSheet(u"border:none;")
        self.dice3.setIconSize(QSize(100, 100))
        self.checkExtra = QCheckBox(self.centralwidget)
        self.checkExtra.setObjectName(u"checkExtra")
        self.checkExtra.setGeometry(QRect(760, 320, 91, 16))
        self.labelRequired = QLabel(self.centralwidget)
        self.labelRequired.setObjectName(u"labelRequired")
        self.labelRequired.setGeometry(QRect(770, 170, 380, 16))
        self.labelPossessed = QLabel(self.centralwidget)
        self.labelPossessed.setObjectName(u"labelPossessed")
        self.labelPossessed.setGeometry(QRect(770, 200, 380, 16))
        self.labelPossessed.setStyleSheet(u"")
        self.labelRolled = QLabel(self.centralwidget)
        self.labelRolled.setObjectName(u"labelRolled")
        self.labelRolled.setGeometry(QRect(770, 260, 380, 16))
        self.labelTotal = QLabel(self.centralwidget)
        self.labelTotal.setObjectName(u"labelTotal")
        self.labelTotal.setGeometry(QRect(770, 230, 380, 16))
        self.labelExtra = QLabel(self.centralwidget)
        self.labelExtra.setObjectName(u"labelExtra")
        self.labelExtra.setEnabled(True)
        self.labelExtra.setGeometry(QRect(1050, 10, 80, 15))
        self.labelResult = QLabel(self.centralwidget)
        self.labelResult.setObjectName(u"labelResult")
        self.labelResult.setGeometry(QRect(770, 290, 380, 16))
        FormGame.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FormGame)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 22))
        self.menuDisplay = QMenu(self.menubar)
        self.menuDisplay.setObjectName(u"menuDisplay")
        self.menuDebug = QMenu(self.menubar)
        self.menuDebug.setObjectName(u"menuDebug")
        FormGame.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(FormGame)
        self.statusbar.setObjectName(u"statusbar")
        FormGame.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menuDisplay.addAction(self.actionShowCollections)
        self.menuDisplay.addAction(self.actionShowAdjustments)
        self.menuDisplay.addAction(self.actionShowCurrentAdjustments)
        self.menuDebug.addAction(self.actionConsole)

        self.retranslateUi(FormGame)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(FormGame)
    # setupUi

    def retranslateUi(self, FormGame):
        FormGame.setWindowTitle(QCoreApplication.translate("FormGame", u"RogueLife2", None))
        self.actionShowCollections.setText(QCoreApplication.translate("FormGame", u"\u85cf\u54c1\u5217\u8868", None))
        self.actionShowAdjustments.setText(QCoreApplication.translate("FormGame", u"\u4fee\u6b63\u5217\u8868", None))
        self.actionShowCurrentAdjustments.setText(QCoreApplication.translate("FormGame", u"\u5f53\u524d\u751f\u6548\u7684\u4fee\u6b63\u5217\u8868", None))
        self.actionConsole.setText(QCoreApplication.translate("FormGame", u"Console", None))
        self.buttonContinue.setText(QCoreApplication.translate("FormGame", u"\u7ee7\u7eed", None))
        self.labelEvent.setText(QCoreApplication.translate("FormGame", u"\u4e8b\u4ef6", None))
        self.labelAction.setText(QCoreApplication.translate("FormGame", u"\u53ef\u9009\u884c\u52a8", None))
        self.labelCheck.setText(QCoreApplication.translate("FormGame", u"\u68c0\u5b9a", None))
        self.labelItems.setText(QCoreApplication.translate("FormGame", u"\u85cf\u54c1\u5217\u8868", None))
        self.labelAdjustments.setText(QCoreApplication.translate("FormGame", u"\u4fee\u6b63\u5217\u8868", None))
        self.labelCurrentAdjustments.setText(QCoreApplication.translate("FormGame", u"\u5f53\u524d\u751f\u6548\u7684\u4fee\u6b63\u5217\u8868(\u542b\u4fee\u6b63\u7cfb\u6570)", None))
        self.buttonReroll.setText(QCoreApplication.translate("FormGame", u"\u91cd\u9ab0", None))
        self.labelInfo.setText(QCoreApplication.translate("FormGame", u"\u4fe1\u606f", None))
        self.labelPossibility.setText(QCoreApplication.translate("FormGame", u"\u68c0\u5b9a\u6210\u529f\u53ef\u80fd\u6027", None))
        self.dice1.setText("")
        self.dice2.setText("")
        self.dice3.setText("")
        self.checkExtra.setText(QCoreApplication.translate("FormGame", u"\u989d\u5916\u9ab0\u5b50", None))
        self.labelRequired.setText("")
        self.labelPossessed.setText("")
        self.labelRolled.setText("")
        self.labelTotal.setText("")
        self.labelExtra.setText(QCoreApplication.translate("FormGame", u"\u989d\u5916\u9ab0\u5b50", None))
        self.labelResult.setText("")
        self.menuDisplay.setTitle(QCoreApplication.translate("FormGame", u"\u5207\u6362\u67e5\u770b\u5217\u8868", None))
        self.menuDebug.setTitle(QCoreApplication.translate("FormGame", u"\u8c03\u8bd5", None))
    # retranslateUi

